services:
  client:
    build:
      context: .
      target: dev
    ports:
      - "8890:8890"
    env_file: .env
    volumes:
      - ./build:/app
      - go-cache:/root/go/pkg/mod

volumes:
  go-cache:
